# Generated by Django 3.2.15 on 2022-11-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0003_auto_20221103_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
