# Generated by Django 3.2.15 on 2023-01-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0005_auto_20221114_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='number_of_people',
            field=models.IntegerField(null=True),
        ),
    ]
