# Generated by Django 3.2.15 on 2023-02-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0007_recipe_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='ingredient_name',
        ),
    ]
