# Generated by Django 3.2.15 on 2023-02-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0008_rename_name_ingredient_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
