# Generated by Django 3.2.15 on 2023-02-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0009_auto_20230215_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linked_recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_recipes', models.ManyToManyField(to='desserts.Recipe')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='desserts.recipe')),
            ],
        ),
    ]
