# Generated by Django 3.2.15 on 2023-02-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0010_linked_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linked_recipes',
            name='linked_recipes',
        ),
        migrations.AddField(
            model_name='linked_recipes',
            name='linked_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked', to='desserts.recipe'),
        ),
        migrations.AlterField(
            model_name='linked_recipes',
            name='recipe',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='desserts.recipe'),
        ),
    ]
