# Generated by Django 3.2.15 on 2023-02-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0011_auto_20230215_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linked_recipes',
            name='recipe',
        ),
        migrations.AddField(
            model_name='linked_recipes',
            name='recipe',
            field=models.ManyToManyField(to='desserts.Recipe'),
        ),
    ]
