# Generated by Django 3.2.15 on 2023-02-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0013_auto_20230215_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_type',
            field=models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('units', 'units'), ('teaspoons', 'teaspoons')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='linked_recipes',
            name='linked_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_recipe', to='desserts.recipe'),
        ),
        migrations.AlterField(
            model_name='linked_recipes',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='desserts.recipe'),
        ),
    ]
