# Generated by Django 3.2.15 on 2022-10-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221026_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_quantity_type',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='friendly_name',
            field=models.CharField(blank=True, default=False, max_length=50, unique=True),
        ),
    ]
