# Generated by Django 3.2.15 on 2022-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221026_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='friendly_name',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, default=False, max_length=50),
        ),
    ]
